# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Projects
    url: projects/
    weight: 10
  - name: Writing
    url: post/
    weight: 20
  - name: CV
    url: cv/
    weight: 30
